### ISSUE TITLE
Example project to replace Austin 311

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/demo#2]
Rough plan:
- Use Needful things
- Try to exhibit lots of different evidence features
- Don't worry too much about using complicated / hacky syntax - the product here is more the front-end than the code used to make it!

**Comment by archiewood** [comment]
@mcrascal @hughess 

A couple of things for some feedback:
- **General look and feel**
- Any ideas for some **additional pages / charts**? 
   - I don't want this to be too busy, but keen to demo enough Evidence features, and have a generally realistic feeling project. 
   - Adding new pages is relatively low effort, but high reward potentially.
- **URL:** currently this project repo is `needful-things` deployed at https://evidence-demo.netlify.app/. The `tutorial` repo is deployed at https://needful-things.netlify.app/. I think some things need renaming to make it clearer. 
   - Potential options:
      - `demo` + https://evidence-demo.netlify.app & `tutorial` + https://evidence-tutorial.netlify.app 
      - `needful-things` + https://needful-things.netlify.app & `tutorial` + https://evidence-tutorial.netlify.app

**Comment by hughess** [comment]
@archiewood this looks great! This has some good ideas in it for components we can build, plus highlights several areas where it looks like we'll need to add features (e.g., number formatting, image support).

On your feedback areas:

**General look and feel**
- I like the look and feel
- On the Marketing Attribution and NPS pages, the metric cards could be a bit denser (spacing between the name, metric, and comparison smaller) so they appear as more distinct items. At the moment, they're close enough to the report text that it's a bit visually confusing. This might be something to tackle as part of a metric card component though!
- A couple of smaller ideas:
    - You might be able to take the bullets out of the list of pages in the “Jump to” section - the emojis almost act as bullets
    - I think you can take out the "Pages" heading on the department overview pages


**Additional pages / charts**
A few ideas, but I'm not sure how difficult they would be (or if they are worth doing):
- Histogram - distribution of NPS scores
- A pareto chart, maybe on product sales
- Under the Sales by Product bar chart, the same bar chart, but with % chg in sales year-over-year
- The heatmap in the community project example was visually appealing - I’m not sure how much of that example is reusable though

**URL**
I'd vote for the first option - `evidence-demo` and `evidence-tutorial`

**Comment by archiewood** [comment]
This is great feedback.

**Look and feel**
- Tweaked the padding on metrics cards
- removed bullets
- removed "pages" headings

**Additional charts**
- Histogram doesn't look great  (see #270), but have got a decent result with a bar chart
- Pareto is possible, but looks a bit weird without a dual axis as the bars are all squished under the line which goes up to 100%. Also labels randomly disappear.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/58074498/169169416-14a86dbf-8a3f-465b-a11d-a5b8863e55bb.png">

- Heatmap looks great in community demo - but is a bit of an Echarts pain

**URL**
Yeah I liked that one too. Updated everything so far except the tutorial website url - as this needs a change in the docs at the same time

**Comment by archiewood** [comment]
Seems like somebody has already set up https://evidence-tutorial.netlify.app/
It's not in the Netlify account though, so assume someone else has set up privately.

I've gone for https://evidencetutorial.netlify.app/ instead!

**Comment by archiewood** [comment]
This is now done with #3
